name: Run Pipeline
run-name: "Run Pipeline: ${{ inputs.tweak_name }} ${{ inputs.app_version }}"
on:
  workflow_dispatch:
    inputs:
      tweak_name:
        description: tweak_name
        required: true
        type: choice
        options:
          - ApolloReborn
          - BHTwitter
          - FacebookGlow
          - InfusePlus
          - MyYouTube
          - RyukGram
          - SCInsta
          - YouMod
          - YTMusicUltimate
      app_version:
        description: app_version
        required: true
        type: string
        default: latest
jobs:
  run_pipeline:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@v7
      - name: Run uv sync
        run: |
          uv sync --locked
      - name: Run brew install
        run: brew install cyan ipapatch
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Run pipeline
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PYTHONUNBUFFERED: 1
        run: |
          uv run altvault pipeline ${{ inputs.tweak_name }} --app-version ${{ inputs.app_version }}
