name: Run Pipeline
run-name: "Run Pipeline: ${{ inputs.tweak_name }} ${{ inputs.app_version }}"
on:
  workflow_dispatch:
    inputs:
      tweak_name:
        description: tweak_name
        required: true
        type: choice
        options:
          - ApolloReborn
          - BHTwitter
          - FacebookGlow
          - InfusePlus
          - MyYouTube
          - RyukGram
          - SCInsta
          - SparkleIG
          - TheacratNFB
          - YouMod
          - YTMusicUltimate
      app_version:
        description: app_version
        required: true
        type: string
        default: latest
jobs:
  run_pipeline:
    runs-on: macos-26
    steps:
      - name: Workaround to silence homebrew aws/tap warning
        run: brew untap aws/tap || true
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Run uv sync
        run: |
          uv sync --locked
      - name: Run brew install
        run: brew install cyan ipapatch dpkg
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Run pipeline
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PYTHONUNBUFFERED: 1
        run: |
          uv run altvault pipeline "${{ inputs.tweak_name }}" --app-version "${{ inputs.app_version }}"
